server:
  port: 8090
management:
#  endpoint:
#    shutdown:
#      enabled: true
#    info:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: monitoring
#        include: health, info, prometheus